using Microsoft.EntityFrameworkCore.Migrations;

namespace MummyMadness.Migrations.Official
{
    public partial class Start : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "Official",
                columns: table => new
                {
                    ID = table.Column<string>(type: "TEXT", nullable: false),
                    Burial_ID = table.Column<string>(type: "TEXT", nullable: true),
                    Maleonthonskull = table.Column<string>(type: "TEXT", nullable: true),
                    YearonSkull = table.Column<string>(type: "TEXT", nullable: true),
                    DayonSkull = table.Column<string>(type: "TEXT", nullable: true),
                    FemaleieldBook = table.Column<string>(type: "TEXT", nullable: true),
                    FemaleieldBookPageNuMaleber = table.Column<string>(type: "TEXT", nullable: true),
                    InitialsoFemaleDataEntryExpert = table.Column<string>(type: "TEXT", nullable: true),
                    InitialsoFemaleDataEntryChecker = table.Column<string>(type: "TEXT", nullable: true),
                    BYUSaMaleple = table.Column<string>(type: "TEXT", nullable: true),
                    BodyAnalysis = table.Column<string>(type: "TEXT", nullable: true),
                    SkullatMaleagazine = table.Column<string>(type: "TEXT", nullable: true),
                    PostcraniaatMaleagazine = table.Column<string>(type: "TEXT", nullable: true),
                    SexSkull2018 = table.Column<string>(name: "Sex\r\n(Skull2018)", type: "TEXT", nullable: true),
                    AgeSkull2018 = table.Column<string>(name: "Age\r\n(Skull\r\n2018)", type: "TEXT", nullable: true),
                    RackandShelFemale = table.Column<string>(type: "TEXT", nullable: true),
                    TOBECONFemaleIRMaleED = table.Column<string>(type: "TEXT", nullable: true),
                    SkullTrauMalea = table.Column<string>(type: "TEXT", nullable: true),
                    PostcraniaTrauMalea = table.Column<string>(type: "TEXT", nullable: true),
                    CribraOrbitala = table.Column<string>(type: "TEXT", nullable: true),
                    PoroticHyperostosis = table.Column<string>(type: "TEXT", nullable: true),
                    PoroticHyperostosisLOCATIONS = table.Column<string>(name: "PoroticHyperostosis(LOCATIONS)", type: "TEXT", nullable: true),
                    MaleetopicSuture = table.Column<string>(type: "TEXT", nullable: true),
                    ButtonOsteoMalea = table.Column<string>(type: "TEXT", nullable: true),
                    OsteologyunknowncoMaleMaleent = table.Column<string>(type: "TEXT", nullable: true),
                    TeMaleporalMaleandibularJointOsteoarthritisTMaleJOA = table.Column<string>(name: "TeMaleporalMaleandibularJointOsteoarthritis(TMaleJOA)", type: "TEXT", nullable: true),
                    LinearHypoplasiaEnaMaleel = table.Column<string>(type: "TEXT", nullable: true),
                    AreaHillburials = table.Column<string>(name: "Area(Hillburials)", type: "TEXT", nullable: true),
                    ToMaleb = table.Column<string>(type: "TEXT", nullable: true),
                    burialareaNorthorSouth = table.Column<long>(type: "INTEGER", nullable: true),
                    burialnors = table.Column<string>(type: "TEXT", nullable: true),
                    burialareaeastorwest = table.Column<long>(type: "INTEGER", nullable: true),
                    burialxeorw = table.Column<string>(type: "TEXT", nullable: true),
                    Square = table.Column<string>(type: "TEXT", nullable: true),
                    BurialNuMaleber = table.Column<long>(type: "INTEGER", nullable: true),
                    burialwesttohead = table.Column<string>(type: "TEXT", nullable: true),
                    burialwesttoFemaleeet = table.Column<string>(type: "TEXT", nullable: true),
                    burialsouthtohead = table.Column<string>(type: "TEXT", nullable: true),
                    burialsouthtoFemaleeet = table.Column<string>(type: "TEXT", nullable: true),
                    burialdepth = table.Column<string>(type: "TEXT", nullable: true),
                    length = table.Column<string>(type: "TEXT", nullable: true),
                    yearexcav = table.Column<string>(type: "TEXT", nullable: true),
                    MaleonthExcavated = table.Column<string>(type: "TEXT", nullable: true),
                    DateExcavated = table.Column<string>(type: "TEXT", nullable: true),
                    burialpreservation = table.Column<string>(type: "TEXT", nullable: true),
                    burialwrapping = table.Column<string>(type: "TEXT", nullable: true),
                    burialadultchild = table.Column<string>(type: "TEXT", nullable: true),
                    GenderCode = table.Column<string>(type: "TEXT", nullable: true),
                    burialgenderMaleethod = table.Column<string>(type: "TEXT", nullable: true),
                    AgeCodeSINGLE = table.Column<string>(type: "TEXT", nullable: true),
                    BurialDirection = table.Column<string>(type: "TEXT", nullable: true),
                    burialageatdeath = table.Column<string>(type: "TEXT", nullable: true),
                    burialageMaleethod = table.Column<string>(type: "TEXT", nullable: true),
                    HairColorCode = table.Column<string>(type: "TEXT", nullable: true),
                    burialhaircolor = table.Column<string>(type: "TEXT", nullable: true),
                    burialsaMalepletaken = table.Column<string>(type: "TEXT", nullable: true),
                    lengthMale = table.Column<string>(name: "length(Male)", type: "TEXT", nullable: true),
                    lengthCMale = table.Column<string>(name: "length(CMale)", type: "TEXT", nullable: true),
                    Goods = table.Column<string>(type: "TEXT", nullable: true),
                    Cluster = table.Column<string>(type: "TEXT", nullable: true),
                    FemaleaceBundle = table.Column<string>(type: "TEXT", nullable: true),
                    OsteologyNotes = table.Column<string>(type: "TEXT", nullable: true),
                    Description = table.Column<string>(type: "TEXT", nullable: true),
                    Rack = table.Column<string>(name: "Rack#", type: "TEXT", nullable: true),
                    Bag = table.Column<string>(name: "Bag#", type: "TEXT", nullable: true),
                    Burial = table.Column<string>(name: "Burial#", type: "TEXT", nullable: true),
                    Biologicalcluster = table.Column<string>(type: "TEXT", nullable: true),
                    PreviouslysaMalepled = table.Column<string>(type: "TEXT", nullable: true),
                    burial_location_NS = table.Column<string>(type: "TEXT", nullable: true),
                    burial_location_EW = table.Column<string>(type: "TEXT", nullable: true),
                    low_pair_NS = table.Column<string>(type: "TEXT", nullable: true),
                    high_pair_NS = table.Column<string>(type: "TEXT", nullable: true),
                    low_pair_EW = table.Column<string>(type: "TEXT", nullable: true),
                    high_pair_EW = table.Column<string>(type: "TEXT", nullable: true),
                    burial_subplot = table.Column<string>(type: "TEXT", nullable: true),
                    east_to_head = table.Column<long>(type: "INTEGER", nullable: true),
                    east_to_Femaleeet = table.Column<long>(type: "INTEGER", nullable: true),
                    burial_situation_notes = table.Column<string>(type: "TEXT", nullable: true),
                    saMaleple_nuMaleber = table.Column<string>(type: "TEXT", nullable: true),
                    gender_GE = table.Column<string>(type: "TEXT", nullable: true),
                    GE_Femaleunction_total = table.Column<string>(type: "TEXT", nullable: true),
                    basilar_suture = table.Column<string>(type: "TEXT", nullable: true),
                    ventral_arc = table.Column<long>(type: "INTEGER", nullable: true),
                    subpubic_angle = table.Column<long>(type: "INTEGER", nullable: true),
                    sciatic_notch = table.Column<long>(type: "INTEGER", nullable: true),
                    pubic_bone = table.Column<long>(type: "INTEGER", nullable: true),
                    preaur_sulcus = table.Column<long>(type: "INTEGER", nullable: true),
                    Maleedial_IP_raMaleus = table.Column<long>(type: "INTEGER", nullable: true),
                    dorsal_pitting = table.Column<long>(type: "INTEGER", nullable: true),
                    FemaleoreMalean_MaleagnuMale = table.Column<string>(type: "TEXT", nullable: true),
                    FemaleeMaleur_head = table.Column<string>(type: "TEXT", nullable: true),
                    huMaleerus_head = table.Column<string>(type: "TEXT", nullable: true),
                    osteophytosis = table.Column<string>(type: "TEXT", nullable: true),
                    pubic_syMalephysis = table.Column<string>(type: "TEXT", nullable: true),
                    FemaleeMaleur_length = table.Column<string>(type: "TEXT", nullable: true),
                    huMaleerus_length = table.Column<string>(type: "TEXT", nullable: true),
                    tibia_length = table.Column<string>(type: "TEXT", nullable: true),
                    robust = table.Column<string>(type: "TEXT", nullable: true),
                    supraorbital_ridges = table.Column<string>(type: "TEXT", nullable: true),
                    orbit_edge = table.Column<string>(type: "TEXT", nullable: true),
                    parietal_bossing = table.Column<string>(type: "TEXT", nullable: true),
                    gonian = table.Column<string>(type: "TEXT", nullable: true),
                    nuchal_crest = table.Column<string>(type: "TEXT", nullable: true),
                    zygoMaleatic_crest = table.Column<string>(type: "TEXT", nullable: true),
                    cranial_suture = table.Column<string>(type: "TEXT", nullable: true),
                    MaleaxiMaleuMale_cranial_length = table.Column<double>(type: "REAL", nullable: true),
                    MaleaxiMaleuMale_cranial_breadth = table.Column<double>(type: "REAL", nullable: true),
                    basion_bregMalea_height = table.Column<double>(type: "REAL", nullable: true),
                    basion_nasion = table.Column<double>(type: "REAL", nullable: true),
                    basion_prosthion_length = table.Column<double>(type: "REAL", nullable: true),
                    bizygoMaleatic_diaMaleeter = table.Column<double>(type: "REAL", nullable: true),
                    nasion_prosthion = table.Column<double>(type: "REAL", nullable: true),
                    MaleaxiMaleuMale_nasal_breadth = table.Column<double>(type: "REAL", nullable: true),
                    interorbital_breadth = table.Column<double>(type: "REAL", nullable: true),
                    artiFemaleacts_description = table.Column<string>(type: "TEXT", nullable: true),
                    hair_color = table.Column<string>(type: "TEXT", nullable: true),
                    preservation_index = table.Column<string>(type: "TEXT", nullable: true),
                    hair_taken = table.Column<string>(type: "TEXT", nullable: true),
                    soFemalet_tissue_taken = table.Column<string>(type: "TEXT", nullable: true),
                    bone_taken = table.Column<string>(type: "TEXT", nullable: true),
                    tooth_taken = table.Column<string>(type: "TEXT", nullable: true),
                    textile_taken = table.Column<string>(type: "TEXT", nullable: true),
                    description_oFemale_taken = table.Column<string>(type: "TEXT", nullable: true),
                    artiFemaleact_Femaleound = table.Column<string>(type: "TEXT", nullable: true),
                    estiMaleate_living_stature = table.Column<string>(type: "TEXT", nullable: true),
                    tooth_attrition = table.Column<string>(type: "TEXT", nullable: true),
                    tooth_eruption = table.Column<string>(type: "TEXT", nullable: true),
                    pathology_anoMalealies = table.Column<string>(type: "TEXT", nullable: true),
                    epiphyseal_union = table.Column<string>(type: "TEXT", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_Official", x => x.ID);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "Official");
        }
    }
}
