using Microsoft.EntityFrameworkCore.Migrations;

namespace MummyMadness.Migrations.INTEX2
{
    public partial class @new : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "official",
                columns: table => new
                {
                    burialid = table.Column<int>(type: "integer", nullable: false),
                    burial_id = table.Column<string>(type: "character varying", nullable: true),
                    maleonth_on_skull = table.Column<string>(type: "character varying", nullable: true),
                    year_on_skull = table.Column<string>(type: "character varying", nullable: true),
                    day_on_skull = table.Column<string>(type: "character varying", nullable: true),
                    femaleield_book = table.Column<string>(type: "character varying", nullable: true),
                    femaleield_book_page_numaleber = table.Column<string>(type: "character varying", nullable: true),
                    initials_ofemale_data_entry_expert = table.Column<string>(type: "character varying", nullable: true),
                    initials_ofemale_data_entry_checker = table.Column<string>(type: "character varying", nullable: true),
                    byu_samaleple = table.Column<string>(type: "character varying", nullable: true),
                    body_analysis = table.Column<string>(type: "character varying", nullable: true),
                    skull_at_maleagazine = table.Column<string>(type: "character varying", nullable: true),
                    postcrania_at_maleagazine = table.Column<string>(type: "character varying", nullable: true),
                    rack_and_shelfemale = table.Column<string>(type: "character varying", nullable: true),
                    to_be_confemaleirmaleed = table.Column<string>(type: "character varying", nullable: true),
                    skull_traumalea = table.Column<string>(type: "character varying", nullable: true),
                    postcrania_traumalea = table.Column<string>(type: "character varying", nullable: true),
                    cribra_orbitala = table.Column<string>(type: "character varying", nullable: true),
                    porotic_hyperostosis = table.Column<string>(type: "character varying", nullable: true),
                    porotic_hyperostosis_locations = table.Column<string>(type: "character varying", nullable: true),
                    maleetopic_suture = table.Column<string>(type: "character varying", nullable: true),
                    button_osteomalea = table.Column<string>(type: "character varying", nullable: true),
                    osteology_unknown_comalemaleent = table.Column<string>(type: "character varying", nullable: true),
                    temaleporal_maleandibular_joint_osteoarthritis = table.Column<string>(type: "character varying", nullable: true),
                    linear_hypoplasia_enamaleel = table.Column<string>(type: "character varying", nullable: true),
                    area = table.Column<string>(type: "character varying", nullable: true),
                    tomaleb = table.Column<string>(type: "character varying", nullable: true),
                    burial_area_northorsouth = table.Column<string>(type: "character varying", nullable: true),
                    burialnors = table.Column<string>(type: "character varying", nullable: true),
                    burial_area_eastorwest = table.Column<string>(type: "character varying", nullable: true),
                    burialxeorw = table.Column<string>(type: "character varying", nullable: true),
                    square = table.Column<string>(type: "character varying", nullable: true),
                    burial_numaleber = table.Column<string>(type: "character varying", nullable: true),
                    burial_westtohead = table.Column<string>(type: "character varying", nullable: true),
                    burial_westtofemaleeet = table.Column<string>(type: "character varying", nullable: true),
                    burial_southtohead = table.Column<string>(type: "character varying", nullable: true),
                    burial_southtofemaleeet = table.Column<string>(type: "character varying", nullable: true),
                    burial_depth = table.Column<string>(type: "character varying", nullable: true),
                    length = table.Column<string>(type: "character varying", nullable: true),
                    year_excav = table.Column<int>(type: "integer", nullable: true),
                    maleonth_excavated = table.Column<string>(type: "character varying", nullable: true),
                    date_excavated = table.Column<string>(type: "character varying", nullable: true),
                    burial_preservation = table.Column<string>(type: "character varying", nullable: true),
                    burial_wrapping = table.Column<string>(type: "character varying", nullable: true),
                    burial_adult_child = table.Column<string>(type: "character varying", nullable: true),
                    gender_code = table.Column<string>(type: "character varying", nullable: true),
                    burialgendermaleethod = table.Column<string>(type: "character varying", nullable: true),
                    age_code_single = table.Column<string>(type: "character varying", nullable: true),
                    burial_direction = table.Column<string>(type: "character varying", nullable: true),
                    burialageatdeath = table.Column<string>(type: "character varying", nullable: true),
                    burialagemaleethod = table.Column<string>(type: "character varying", nullable: true),
                    hair_color_code = table.Column<string>(type: "character varying", nullable: true),
                    burialhaircolor = table.Column<string>(type: "character varying", nullable: true),
                    burialsamalepletaken = table.Column<string>(type: "character varying", nullable: true),
                    length_male = table.Column<string>(type: "character varying", nullable: true),
                    goods = table.Column<string>(type: "character varying", nullable: true),
                    cluster = table.Column<string>(type: "character varying", nullable: true),
                    femaleace_bundle = table.Column<string>(type: "character varying", nullable: true),
                    osteology_notes = table.Column<string>(type: "character varying", nullable: true),
                    description = table.Column<string>(type: "character varying", nullable: true),
                    rack = table.Column<string>(type: "character varying", nullable: true),
                    bag = table.Column<string>(type: "character varying", nullable: true),
                    burial = table.Column<string>(type: "character varying", nullable: true),
                    biological_cluster = table.Column<string>(type: "character varying", nullable: true),
                    previously_samalepled = table.Column<string>(type: "character varying", nullable: true),
                    burial_location_ns = table.Column<string>(type: "character varying", nullable: true),
                    burial_location_ew = table.Column<string>(type: "character varying", nullable: true),
                    low_pair_ns = table.Column<string>(type: "character varying", nullable: true),
                    high_pair_ns = table.Column<string>(type: "character varying", nullable: true),
                    low_pair_ew = table.Column<string>(type: "character varying", nullable: true),
                    high_pair_ew = table.Column<string>(type: "character varying", nullable: true),
                    burial_subplot = table.Column<string>(type: "character varying", nullable: true),
                    east_to_head = table.Column<string>(type: "character varying", nullable: true),
                    east_to_femaleeet = table.Column<string>(type: "character varying", nullable: true),
                    burial_situation_notes = table.Column<string>(type: "character varying", nullable: true),
                    samaleple_numaleber = table.Column<string>(type: "character varying", nullable: true),
                    gender_ge = table.Column<string>(type: "character varying", nullable: true),
                    ge_femaleunction_total = table.Column<string>(type: "character varying", nullable: true),
                    basilar_suture = table.Column<string>(type: "character varying", nullable: true),
                    ventral_arc = table.Column<string>(type: "character varying", nullable: true),
                    subpubic_angle = table.Column<string>(type: "character varying", nullable: true),
                    sciatic_notch = table.Column<string>(type: "character varying", nullable: true),
                    pubic_bone = table.Column<string>(type: "character varying", nullable: true),
                    preaur_sulcus = table.Column<string>(type: "character varying", nullable: true),
                    maleedial_ip_ramaleus = table.Column<string>(type: "character varying", nullable: true),
                    dorsal_pitting = table.Column<string>(type: "character varying", nullable: true),
                    femaleoremalean_maleagnumale = table.Column<string>(type: "character varying", nullable: true),
                    femaleemaleur_head = table.Column<string>(type: "character varying", nullable: true),
                    humaleerus_head = table.Column<string>(type: "character varying", nullable: true),
                    osteophytosis = table.Column<string>(type: "character varying", nullable: true),
                    pubic_symalephysis = table.Column<string>(type: "character varying", nullable: true),
                    femaleemaleur_length = table.Column<string>(type: "character varying", nullable: true),
                    humaleerus_length = table.Column<string>(type: "character varying", nullable: true),
                    tibia_length = table.Column<string>(type: "character varying", nullable: true),
                    robust = table.Column<string>(type: "character varying", nullable: true),
                    supraorbital_ridges = table.Column<string>(type: "character varying", nullable: true),
                    orbit_edge = table.Column<string>(type: "character varying", nullable: true),
                    parietal_bossing = table.Column<string>(type: "character varying", nullable: true),
                    gonian = table.Column<string>(type: "character varying", nullable: true),
                    nuchal_crest = table.Column<string>(type: "character varying", nullable: true),
                    zygomaleatic_crest = table.Column<string>(type: "character varying", nullable: true),
                    cranial_suture = table.Column<string>(type: "character varying", nullable: true),
                    maleaximaleumale_cranial_length = table.Column<string>(type: "character varying", nullable: true),
                    maleaximaleumale_cranial_breadth = table.Column<string>(type: "character varying", nullable: true),
                    basion_bregmalea_height = table.Column<string>(type: "character varying", nullable: true),
                    basion_nasion = table.Column<string>(type: "character varying", nullable: true),
                    basion_prosthion_length = table.Column<string>(type: "character varying", nullable: true),
                    bizygomaleatic_diamaleeter = table.Column<string>(type: "character varying", nullable: true),
                    nasion_prosthion = table.Column<string>(type: "character varying", nullable: true),
                    maleaximaleumale_nasal_breadth = table.Column<string>(type: "character varying", nullable: true),
                    interorbital_breadth = table.Column<string>(type: "character varying", nullable: true),
                    artifemaleacts_description = table.Column<string>(type: "character varying", nullable: true),
                    hair_color = table.Column<string>(type: "character varying", nullable: true),
                    preservation_index = table.Column<string>(type: "character varying", nullable: true),
                    hair_taken = table.Column<string>(type: "character varying", nullable: true),
                    sofemalet_tissue_taken = table.Column<string>(type: "character varying", nullable: true),
                    bone_taken = table.Column<string>(type: "character varying", nullable: true),
                    tooth_taken = table.Column<string>(type: "character varying", nullable: true),
                    textile_taken = table.Column<string>(type: "character varying", nullable: true),
                    description_ofemale_taken = table.Column<string>(type: "character varying", nullable: true),
                    artifemaleact_femaleound = table.Column<string>(type: "character varying", nullable: true),
                    estimaleate_living_stature = table.Column<string>(type: "character varying", nullable: true),
                    tooth_attrition = table.Column<string>(type: "character varying", nullable: true),
                    tooth_eruption = table.Column<string>(type: "character varying", nullable: true),
                    pathology_anomalealies = table.Column<string>(type: "character varying", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("official_pkey", x => x.burialid);
                });
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "official");
        }
    }
}
