using System;
using System.Collections.Generic;

#nullable disable

namespace MummyMadness.Models
{
    public partial class Official
    {
        public int Burialid { get; set; }
        public string BurialId1 { get; set; }
        public string MaleonthOnSkull { get; set; }
        public string YearOnSkull { get; set; }
        public string DayOnSkull { get; set; }
        public string FemaleieldBook { get; set; }
        public string FemaleieldBookPageNumaleber { get; set; }
        public string InitialsOfemaleDataEntryExpert { get; set; }
        public string InitialsOfemaleDataEntryChecker { get; set; }
        public string ByuSamaleple { get; set; }
        public string BodyAnalysis { get; set; }
        public string SkullAtMaleagazine { get; set; }
        public string PostcraniaAtMaleagazine { get; set; }
        public string RackAndShelfemale { get; set; }
        public string ToBeConfemaleirmaleed { get; set; }
        public string SkullTraumalea { get; set; }
        public string PostcraniaTraumalea { get; set; }
        public string CribraOrbitala { get; set; }
        public string PoroticHyperostosis { get; set; }
        public string PoroticHyperostosisLocations { get; set; }
        public string MaleetopicSuture { get; set; }
        public string ButtonOsteomalea { get; set; }
        public string OsteologyUnknownComalemaleent { get; set; }
        public string TemaleporalMaleandibularJointOsteoarthritis { get; set; }
        public string LinearHypoplasiaEnamaleel { get; set; }
        public string Area { get; set; }
        public string Tomaleb { get; set; }
        public string BurialAreaNorthorsouth { get; set; }
        public string Burialnors { get; set; }
        public string BurialAreaEastorwest { get; set; }
        public string Burialxeorw { get; set; }
        public string Square { get; set; }
        public string BurialNumaleber { get; set; }
        public string BurialWesttohead { get; set; }
        public string BurialWesttofemaleeet { get; set; }
        public string BurialSouthtohead { get; set; }
        public string BurialSouthtofemaleeet { get; set; }
        public string BurialDepth { get; set; }
        public string Length { get; set; }
        public string? YearExcav { get; set; }
        public string MaleonthExcavated { get; set; }
        public string DateExcavated { get; set; }
        public string BurialPreservation { get; set; }
        public string BurialWrapping { get; set; }
        public string BurialAdultChild { get; set; }
        public string GenderCode { get; set; }
        public string Burialgendermaleethod { get; set; }
        public string AgeCodeSingle { get; set; }
        public string BurialDirection { get; set; }
        public string Burialageatdeath { get; set; }
        public string Burialagemaleethod { get; set; }
        public string HairColorCode { get; set; }
        public string Burialhaircolor { get; set; }
        public string Burialsamalepletaken { get; set; }
        public string LengthMale { get; set; }
        public string Goods { get; set; }
        public string Cluster { get; set; }
        public string FemaleaceBundle { get; set; }
        public string OsteologyNotes { get; set; }
        public string Description { get; set; }
        public string Rack { get; set; }
        public string Bag { get; set; }
        public string Burial { get; set; }
        public string BiologicalCluster { get; set; }
        public string PreviouslySamalepled { get; set; }
        public string BurialLocationNs { get; set; }
        public string BurialLocationEw { get; set; }
        public string LowPairNs { get; set; }
        public string HighPairNs { get; set; }
        public string LowPairEw { get; set; }
        public string HighPairEw { get; set; }
        public string BurialSubplot { get; set; }
        public string EastToHead { get; set; }
        public string EastToFemaleeet { get; set; }
        public string BurialSituationNotes { get; set; }
        public string SamalepleNumaleber { get; set; }
        public string GenderGe { get; set; }
        public string GeFemaleunctionTotal { get; set; }
        public string BasilarSuture { get; set; }
        public string VentralArc { get; set; }
        public string SubpubicAngle { get; set; }
        public string SciaticNotch { get; set; }
        public string PubicBone { get; set; }
        public string PreaurSulcus { get; set; }
        public string MaleedialIpRamaleus { get; set; }
        public string DorsalPitting { get; set; }
        public string FemaleoremaleanMaleagnumale { get; set; }
        public string FemaleemaleurHead { get; set; }
        public string HumaleerusHead { get; set; }
        public string Osteophytosis { get; set; }
        public string PubicSymalephysis { get; set; }
        public string FemaleemaleurLength { get; set; }
        public string HumaleerusLength { get; set; }
        public string TibiaLength { get; set; }
        public string Robust { get; set; }
        public string SupraorbitalRidges { get; set; }
        public string OrbitEdge { get; set; }
        public string ParietalBossing { get; set; }
        public string Gonian { get; set; }
        public string NuchalCrest { get; set; }
        public string ZygomaleaticCrest { get; set; }
        public string CranialSuture { get; set; }
        public string MaleaximaleumaleCranialLength { get; set; }
        public string MaleaximaleumaleCranialBreadth { get; set; }
        public string BasionBregmaleaHeight { get; set; }
        public string BasionNasion { get; set; }
        public string BasionProsthionLength { get; set; }
        public string BizygomaleaticDiamaleeter { get; set; }
        public string NasionProsthion { get; set; }
        public string MaleaximaleumaleNasalBreadth { get; set; }
        public string InterorbitalBreadth { get; set; }
        public string ArtifemaleactsDescription { get; set; }
        public string HairColor { get; set; }
        public string PreservationIndex { get; set; }
        public string HairTaken { get; set; }
        public string SofemaletTissueTaken { get; set; }
        public string BoneTaken { get; set; }
        public string ToothTaken { get; set; }
        public string TextileTaken { get; set; }
        public string DescriptionOfemaleTaken { get; set; }
        public string ArtifemaleactFemaleound { get; set; }
        public string EstimaleateLivingStature { get; set; }
        public string ToothAttrition { get; set; }
        public string ToothEruption { get; set; }
        public string PathologyAnomalealies { get; set; }
    }
}
